---

- name: copy simplesnap scripts
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "a+x"
  with_items:
    - simplesnap
    - simplesnapwrap

- name: create ssh key for simplesnap
  user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_bits: "2048"
    ssh_key_file: ".ssh/simplesnap"

- name: Create cron task for polling backups
  cron:
    minute: "{{ item.simplesnap_minute|default('23') }}"
    hour: "{{ item.simplesnap_hour|default('01') }}"
    day: "{{ item.simplesnap_day|default('*') }}"
    month: "{{ item.simplesnap_month|default('*') }}"
    dow: "{{ item.simplesnap_dow|default('*') }}"
    user: "{{ item.simplesnap_user|default(user) }}"
    name: "{{ item.simplesnap_cron_file|default(cron_file) }}"
    cron_file: "{{ item.simplesnap_cron_file|default(cron_file) }}"
    job: "/usr/local/sbin/simplesnap {{ item.simplesnap_remotehost }} --setname {{ item.simplesnap_setname|default('mainset') }} --store {{ item.simplesnap_store|default('tank/backup') }}"
    backup: yes
    state: present
  with_items: "{{ simplesnap_jobs }}"
